name: multimodal-captions-2
channels:
  - pytorch
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - datasets
  - python=3.10
  - pytorch
  - torchvision
  - tqdm
  - transformers
  - wandb
  - einops
  - libjpeg-turbo
